# Generated by Django 3.1.4 on 2020-12-21 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_auto_20201221_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 21)),
        ),
    ]
