# Generated by Django 3.1.4 on 2020-12-21 22:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_auto_20201221_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransfer',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 22, 36, 21, 567760, tzinfo=utc)),
        ),
    ]
